// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubEffectServiceClient is the client API for SubEffectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubEffectServiceClient interface {
	Create(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
}

type subEffectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubEffectServiceClient(cc grpc.ClientConnInterface) SubEffectServiceClient {
	return &subEffectServiceClient{cc}
}

func (c *subEffectServiceClient) Create(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, "/api.SubEffectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubEffectServiceServer is the server API for SubEffectService service.
// All implementations must embed UnimplementedSubEffectServiceServer
// for forward compatibility
type SubEffectServiceServer interface {
	Create(context.Context, *UpsertRequest) (*UpsertResponse, error)
	mustEmbedUnimplementedSubEffectServiceServer()
}

// UnimplementedSubEffectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubEffectServiceServer struct {
}

func (UnimplementedSubEffectServiceServer) Create(context.Context, *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSubEffectServiceServer) mustEmbedUnimplementedSubEffectServiceServer() {}

// UnsafeSubEffectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubEffectServiceServer will
// result in compilation errors.
type UnsafeSubEffectServiceServer interface {
	mustEmbedUnimplementedSubEffectServiceServer()
}

func RegisterSubEffectServiceServer(s grpc.ServiceRegistrar, srv SubEffectServiceServer) {
	s.RegisterService(&SubEffectService_ServiceDesc, srv)
}

func _SubEffectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubEffectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SubEffectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubEffectServiceServer).Create(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubEffectService_ServiceDesc is the grpc.ServiceDesc for SubEffectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubEffectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SubEffectService",
	HandlerType: (*SubEffectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SubEffectService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/etemplate.proto",
}
